#!/bin/bash

shopt -s extglob

die() { local -i e=$1 ; printf >&2 '%s\n' "${*:2}" ; exit "$e" ; }

(( true = 0==0, false = !true ))

slurp=false
input=
output=

for ((;$#;)) do
    case $1 in
    --slurp)    slurp=true ;;
    --input=*)  input=${1#*=} ;;
    --output=*) output=${1#*=} ;;
    --*)        die 64 "Invalid option '$1'" ;;                         # EX_USAGE
    *)          break ;;
    esac
    shift
done

[[ $input  ]] || { input=$1  ; shift ; }
[[ $output ]] || { output=$1 ; shift ; }

(( $# == 0 )) || die 64 'Too many args'                                 # EX_USAGE

[[ $input  ]] || die 64 'Missing input arg 1'                           # EX_USAGE
[[ $output ]] || (( slurp )) || die 64 'Missing output arg 2'           # EX_USAGE

IFS= read -r shbang < "$input" &&
[[ $shbang = '#!'* ]] || die 65 'input does not start with #! line'     # EX_DATAERR
shbang=${shbang##'#!'*(' ')}
IFS=$' \t' read -r shbang shbangopts <<< "$shbang"
interp=${shbang##*/}

if (( verbose )) ; then
    printf >&2 'shbang=%s\n' "$shbang"
fi

if [[ $output = ?(-) ]]
then
    :   # stdout
elif (( slurp ))
then
    : "${output:=$input}"   # overwrite input if slurp and no output specified

    command -v slurp 2>/dev/null ||
    slurp() {
        local output="$2" # ignore -o
        local tmp=/tmp/slurp.$$.$RANDOM
        cat > "$tmp" &&
        cat < "$tmp" > "$output"
        rm -f "$tmp"
    }
    exec > >( slurp -o "$output" )
else
    [[ $input -ef $output ]] && die 65 'Input and output must not be the same file without --slurp'     # EX_DATAERR
    exec > "$output"
fi

preamble=\
'#!/bin/sh -e
{
interp=$( command -v "INTERP" )
self=$0
printf "#!%sINTOPTS\n# %-*s #\n" "$interp" \
        $((SIZE-${#interp})) "(this blank line for http://noenv.github.io)" |
        #  SIZE is the byte offset of the line following the next "}" line
dd of="$self" conv=notrunc 2>/dev/null
exec "$0" "$@"
}
'

preamble="${preamble/INTERP/$interp}"
preamble="${preamble/INTOPTS/${shbangopts:+ $shbangopts}}"

# "$size" replaces "SIZE" so make sure it's 4 bytes (including padding spaces)
printf -v size '%-4u' $(( ${#preamble} - 11 ))

preamble="${preamble//SIZE/$size}"

printf %s "$preamble"
tail -n+2 "$input"
